// Code generated by goctl. DO NOT EDIT.
package types

type AddUserRequest struct {
	Tel      string `form:"tel"`
	NickName string `form:"nick_name"`
}

type AddUserResponse struct {
	Id int64 `form:"id"`
	AddUserRequest
}

type DelUserRequest struct {
	Id int64 `form:"id"`
}

type DelUserResponse struct {
	Id int64 `form:"id"`
}

type EditUserRequest struct {
	Id       int64  `form:"id"`
	Tel      string `form:"tel"`
	NickName string `form:"nick_name"`
}

type EditUserResponse struct {
	Id int64 `form:"id"`
	EditUserRequest
}

type UserInfoRequest struct {
	Id int64 `form:"id"`
}

type UserInfoResponse struct {
	Tel      string `form:"tel"`
	NickName string `form:"nick_name"`
}
