// Code generated by goctl. DO NOT EDIT.
package types

type UserInfoRequest struct {
	UserId int64 `form:"userId"`
}

type UserInfoResponse struct {
	UserId   int64  `form:"userId"`
	Nickname string `form:"nickname"`
}
